#!/bin/bash

#create container f5-hello-world
kubectl create -f f5-hello-world-deployment.yaml
kubectl create -f f5-hello-world-service-clusterip.yaml
kubectl create -f f5-hello-world-configmap.yaml

