#!/bin/bash

#delete kubernetes dashboard, authentication and RBAC
kubectl delete -f kube-dashboard.yaml
kubectl delete clusterrolebinding kubernetes-dashboard -n kube-system
kubectl delete serviceaccount kubernetes-dashboard -n kube-system
