#!/bin/bash

#delete kubernetes bigip container connecter, authentication and RBAC 
oc delete -f f5-nodeport-deployment.yaml
oc delete clusterrolebinding k8s-bigip-ctlr-clusteradmin
oc delete serviceaccount k8s-bigip-ctlr -n kube-system
oc delete secret bigip-login -n kube-system

