apiVersion: v1
kind: ConfigMap
metadata:
  # name of the resource to create on the BIG-IP
  name: f5k8s2.vs
  # the namespace to create the object in; must match the namespace of the
  # service you want to proxy and the namespace the k8s-bigip-ctlr is
  # configured to watch
  namespace: demoproject
  labels:
    # the type of resource you want to create on the BIG-IP
    f5type: virtual-server
data:
  schema: "f5schemadb://bigip-virtual-server_v0.1.7.json"
  data: |
    {
      "virtualServer": {
        "backend": {
          "servicePort": 8080,
          "serviceName": "deployment-example",
          "healthMonitors": [{
            "interval": 30,
            "protocol": "http",
            "send": "GET",
            "timeout": 86400
          }]
        },
        "frontend": {
          "virtualAddress": {
            "port": 80,
            "bindAddr": "10.10.199.99"
          },
          "partition": "ose",
          "balance": "round-robin",
          "mode": "http"
        }
      }
    }
